project_name: kubectl-trace
before:
  hooks:
    - go mod tidy
builds:
  - id: "kubectl-trace"
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - arm64
    - 386
    main: ./cmd/kubectl-trace
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    ldflags: |
      -X github.com/iovisor/kubectl-trace/pkg/version.buildTime={{ .Timestamp }}
      -X github.com/iovisor/kubectl-trace/pkg/version.gitCommit={{ .Commit }}
      -X github.com/iovisor/kubectl-trace/pkg/cmd.ImageTag={{ .Commit }}
      -X github.com/iovisor/kubectl-trace/pkg/cmd.InitImageTag={{ .Commit }}
    binary: kubectl-trace
  - id: "trace-runner"
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - arm64
    - 386
    main: ./cmd/trace-runner
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    ldflags: |
      -X github.com/iovisor/kubectl-trace/pkg/version.buildTime={{ .Timestamp }}
      -X github.com/iovisor/kubectl-trace/pkg/version.gitCommit={{ .Commit }}
      -X github.com/iovisor/kubectl-trace/pkg/cmd.ImageTag={{ .Commit }}
      -X github.com/iovisor/kubectl-trace/pkg/cmd.InitImageTag={{ .Commit }}
    binary: trace-runner

archives:
  - id: "kubectl-trace"
    builds:
    - "kubectl-trace"
    name_template: 'kubectl-trace_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
    - goos: windows
      format: zip

snapshot:
  name_template: 'master'

release:
  github:
  prerelease: auto
