apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: trace
spec:
  version: {{ .TagName }}
  homepage: https://github.com/iovisor/kubectl-trace
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-trace
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-trace
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-trace
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-trace
  - selector:
      matchLabels:
        os: linux
        arch: 386
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_linux_386.tar.gz" .TagName }}
    bin: kubectl-trace
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_windows_amd64.zip" .TagName }}
    bin: kubectl-trace.exe
  - selector:
      matchLabels:
        os: windows
        arch: 386
    {{addURIAndSha "https://github.com/iovisor/kubectl-trace/releases/download/{{ .TagName }}/kubectl-trace_{{ .TagName }}_windows_386.zip" .TagName }}
    bin: kubectl-trace.exe
  shortDescription: Trace Kubernetes pods and nodes with system tools
  description: |
    This plugin is used to analyze production systems and Kubernetes workloads
    by scheduling a trace job on a target node or alongside a target pod in
    order to analyze it with eBPF and other tracing and profiling technologies.
